name: "PEM to JWT"
description: "Generate a JWT token from a provided PEM key"
author: "Johan Ekman"

inputs:
  key:
    description: "The PEM key to use"
  id:
    description: "The ID of the App"
outputs:
  jwt:
    description: "The JWT token created from the provided PEM key"

runs:
  using: "docker"
  image: "Dockerfile"