name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: ekke020/fetch-jwt@master
        with: 
          key: ${{ secrets.TEST_KEY }}
          id: ${{ secrets.TEST_ID }}
      - name: Validate token
        run: |
          if ! [[ "${{ steps.selftest.outputs.token }}" !=~ ^ey([a-zA-Z0-9_=]+).([a-zA-Z0-9_=]+).([a-zA-Z0-9_\-]*)$ ]]; then 
            exit 1
          fi
          
