name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: ekke020/fetch-jwt@master
        with: 
          key: ${{ secrets.TEST_KEY }}
          id: ${{ secrets.TEST_ID }}
      - name: Validate token
        run: |
          if ! [[ "${{ steps.selftest.outputs.token }}" =~ ^ey([a-zA-Z0-9_=]+).([a-zA-Z0-9_=]+).([a-zA-Z0-9_\-]*)$ ]]; then 
            exit 1
          fi
          
